# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# Docker needed to run shellcheck inside the container.
# image: atlassian/default-image:latest

options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - make test